# Generated by Django 5.1.1 on 2024-10-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
