# Generated by Django 5.1.1 on 2024-11-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='deck',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='discard_pile',
            field=models.JSONField(default=list),
        ),
    ]
