# Generated by Django 5.1.1 on 2024-11-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_deck_room_discard_pile'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
