# Generated by Django 5.1.1 on 2024-11-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_last_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='problem_card',
            field=models.JSONField(default=list),
        ),
    ]
