# Generated by Django 5.1.1 on 2024-11-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_room_last_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='turn_list',
            field=models.JSONField(default=list),
        ),
    ]
