# Generated by Django 5.1.1 on 2024-11-04 17:05

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_room_turn_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rule',
            field=models.JSONField(default=game.models.default_rule),
        ),
    ]
