# Generated by Django 5.1.1 on 2024-11-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_room_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='center',
            field=models.JSONField(default=list),
        ),
    ]
